### ISSUE TITLE
panic: sync: negative WaitGroup counter

### ISSUE THREAD

**Issue by Ovi3** [Ciyfly/Argo#18]
`./argo -f /tmp/domains.txt --format txt --proxy http://127.0.0.1:7777`

似乎一出现超时就崩 `[timeout tab ] => https://xxx.com/H7ocmnf12x`
```
panic: sync: negative WaitGroup counter

goroutine 110 [running]:
sync.(*WaitGroup).Add(0xc0001286e0?, 0xc0000e9d68?)
        /opt/hostedtoolcache/go/1.19.11/x64/src/sync/waitgroup.go:83 +0xda
sync.(*WaitGroup).Done(...)
        /opt/hostedtoolcache/go/1.19.11/x64/src/sync/waitgroup.go:108
argo/pkg/engine.(*EngineInfo).closeTab(0xc0001a0000, 0xc0001286e0, 0x4, 0x3, 0x0?)
        /home/runner/work/Argo/Argo/pkg/engine/tab.go:57 +0x279
argo/pkg/engine.(*EngineInfo).NormalCloseTab(...)
        /home/runner/work/Argo/Argo/pkg/engine/tab.go:62
argo/pkg/engine.(*EngineInfo).NewTab.func1()
        /home/runner/work/Argo/Argo/pkg/engine/tab.go:88 +0x7e5
created by argo/pkg/engine.(*EngineInfo).NewTab
        /home/runner/work/Argo/Argo/pkg/engine/tab.go:81 +0x1aa

```

**Comment by Ciyfly** [comment]
> 

使用的是最新版的吗 能提供下系统 平台和目标吗

**Comment by Ovi3** [comment]
argo 1.2.12
ubuntu 20.04
