### ISSUE TITLE
debian 10 vps 报错，内存充足

### ISSUE THREAD

**Issue by ghost** [Ciyfly/Argo#20]
```
root@soapsbounty4H8Gdebian:~# ./argo -f alldomains_origin_urls.txt  --format txt
[2023-10-20 16:17:44] [info]  [argo start]
/2023-10-20 16:17:44] [info]  target: http://qq.travel
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x90628f]

goroutine 1 [running]:
argo/pkg/req.getHttpClient({0xc0000be3c0?, 0xc0000e0040?}, {0xb32f55?, 0xc000062030?})
        /github/workspace/pkg/req/req.go:23 +0x4f
argo/pkg/req.CheckTarget({0xc0000be3c0?, 0x4?})
        /github/workspace/pkg/req/req.go:43 +0x47
main.RunMain(0xc0000d0160?)
        /github/workspace/cmd/argo.go:252 +0x28e
github.com/urfave/cli/v2.(*Command).Run(0xc0000d0160, 0xc000092080, {0xc00012c000, 0x5, 0x5})
        /go/pkg/mod/github.com/urfave/cli/v2@v2.24.4/command.go:273 +0xa42
github.com/urfave/cli/v2.(*App).RunContext(0xc0000a4000, {0xfd5d78?, 0xc00012e000}, {0xc00012c000, 0x5, 0x5})
        /go/pkg/mod/github.com/urfave/cli/v2@v2.24.4/app.go:332 +0x616
github.com/urfave/cli/v2.(*App).Run(...)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.24.4/app.go:309
main.main()
        /github/workspace/cmd/argo.go:219 +0x1469
root@soapsbounty4H8Gdebian:~# ./argo -v
argo version v1.2.13
root@soapsbounty4H8Gdebian:~# 
```

**Comment by Ciyfly** [comment]
可以尝试用下最新版试试
